fix: proper path to archetype handling

diff --git a/src/lupin b/src/lupin
--- a/src/lupin
+++ b/src/lupin
@@ -1,49 +1,49 @@
 #!/bin/bash
 
 REQUIRED_TOOLS=(
-  hugo
+    hugo
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
-  if ! command -v "${TOOL}" >/dev/null; then
-    echo "${TOOL} is required... "
-    exit 1
-  fi
+    if ! command -v "${TOOL}" >/dev/null; then
+        echo "${TOOL} is required... "
+        exit 1
+    fi
 done
 
 SCRIPTPATH="$(
-  cd "$(dirname "$0")" >/dev/null 2>&1 || exit
-  pwd -P
+    cd "$(dirname "$0")" >/dev/null 2>&1 || exit
+    pwd -P
 )"
 CURPATH="$(pwd -P)"
 
 PS3='Choose section: '
 OPTIONS=("Post" "Music to program to" "Notes from the Lab" "Hugo Release Notes" "Tag" "Quit")
 select opt in "${OPTIONS[@]}"; do
-  case $opt in
-  "Post")
-    source $SCRIPTPATH/archetypes/post
-    exit
-    ;;
-  "Music to program to")
-    source $SCRIPTPATH/archetypes/music2program2
-    exit
-    ;;
-  "Notes from the Lab")
-    source $SCRIPTPATH/archetypes/notes-from-the-lab
-    exit
-    ;;
-  "Hugo Release Notes")
-    source $SCRIPTPATH/archetypes/hugo-release-notes
-    exit
-    ;;
-  "Tag")
-    source $SCRIPTPATH/archetypes/tag
-    exit
-    ;;
-  "Quit")
-    break
-    ;;
-  *) echo "invalid option $REPLY" ;;
-  esac
+    case $opt in
+        "Post")
+            source $SCRIPTPATH/new/post
+            exit
+        ;;
+        "Music to program to")
+            source $SCRIPTPATH/new/music2program2
+            exit
+        ;;
+        "Notes from the Lab")
+            source $SCRIPTPATH/new/notes-from-the-lab
+            exit
+        ;;
+        "Hugo Release Notes")
+            source $SCRIPTPATH/new/hugo-release-notes
+            exit
+        ;;
+        "Tag")
+            source $SCRIPTPATH/new/tag
+            exit
+        ;;
+        "Quit")
+            break
+        ;;
+        *) echo "invalid option $REPLY" ;;
+    esac
 done
